### ISSUE TITLE
Consulta Fundamentos JavaScript I 

### ISSUE THREAD

**Issue by usuario1-AERG2526** [usuario1-AERG2223/practica_dwec_gestor_presupuesto_Asensio_Rebollo#1]
@pedroprieto.Estoy haciendo la práctica de Fundamentos.
Hay dos apartados que no consigo pasar los test:

1.-CrearGasto devuelve un objeto gasto con valor 0 si el parámetro valor no es un número positivo y

2.-Método 'actualizarValor' del objeto gasto.
Seguramente irán asociados, porque los dos tiene que ver si el número es menor que 0.

Otras dudas, hasta que no acabe la práctica, no se hace Pull Request??

Gracias

**Comment by usuario1-AERG2526** [comment]
@pedroprieto.Comprueba mi práctica

**Comment by pedroprieto** [comment]
@usuario1-AERG2223 , buenas. Tienes que poner @pedroprieto sin el punto a continuación, dejando un espacio en blanco. Al mostrarse el mensaje, tiene que aparecer destacado, como en el mío.

**Comment by pedroprieto** [comment]
- Es correcto: la PR tienes que hacerla al acabar la práctica. Aunque si tienes dudas, también puedes abrirla, en lugar del issue.
- En `CrearGasto`, esta condición no cumple los requisitos: tienes que evaluar el parámetro `valor` por separado, y asignar `0` si no es número o es menor que cero. Pero sin relacionarlo con `descripcion`. Es decir, utiliza un `if` aparte solo para eso.
  https://github.com/usuario1-AERG2223/practica_dwec_gestor_presupuesto_Asensio_Rebollo/blob/f32144105031ffea289bf20f3124f85a8bce0539/js/gestionPresupuesto.js#L29
- En este código, ¿dónde está definida la variable `valor`?
  https://github.com/usuario1-AERG2223/practica_dwec_gestor_presupuesto_Asensio_Rebollo/blob/f32144105031ffea289bf20f3124f85a8bce0539/js/gestionPresupuesto.js#L51
  O bien pones `this.valor = this.valor`, o mejor, no pones nada en el `else`.

Ánimo y un saludo!!
